### ISSUE TITLE
var a={};a.b=a;clone(a);这种循环引用将报错

### ISSUE THREAD

**Issue by yangdan8** [pvorb/clone#107]
var a={};a.b=a;clone(a);这种循环引用将报错

**Comment by pvorb** [comment]
Translation from Google:

> This circular reference will give an error

**Comment by pvorb** [comment]
It doesn't give an error for me:

~~~
$ node
> var clone = require('clone');
undefined
> var a={};a.b=a;clone(a);
{ b: [Circular] }
~~~

Are you sure you are using this package? And if so, what version are you using?

**Comment by yangdan8** [comment]
I saw easytable reference your deepclone infinite loop, it is estimated that this problem, sorry, did not look at the specific logic in detail
