### ISSUE TITLE
Fix the "build unknown" issue

### ISSUE THREAD

**Issue by vajahath** [pvorb/clone#75]
At [npm clone website](https://www.npmjs.com/package/clone) the build is failing [![build status](https://secure.travis-ci.org/pvorb/node-clone.svg)](http://travis-ci.org/pvorb/node-clone).

Seems like you used `travis-ci.org/pvorb/node-clone/` instead of `travis-ci.org/pvorb/clone`.

**Comment by pvorb** [comment]
I know, but the only way to fix it would be to publish a new release.

**Comment by vajahath** [comment]
You can release it by a patch update.
Let it move from 2.1.0 to 2.1.1 and mention it on change log.
This looks necessary, bcz the "build unknown" passes wrong message to audience and leaves bad impression.
