### ISSUE TITLE
When try clone cheerio element get TypeError

### ISSUE THREAD

**Issue by gefalko** [pvorb/clone#79]
`clone(element, true)`
TypeError: Cannot set property firstChild of #<Object> which has only a getter

**Comment by pvorb** [comment]
What is a cheerio element?

**Comment by gefalko** [comment]
https://github.com/cheeriojs/cheerio

Cheerio is implementation of core jQuery

const $ = cheerio.load(html);
let element = $('#elemnt-id');
clone(element, true)

**Comment by pvorb** [comment]
Fixed by #91
