### ISSUE TITLE
minified version for unpkg

### ISSUE THREAD

**Issue by janat08** [pvorb/clone#89]
Please commit minified version of files for CDN unpkg.

**Comment by jimaek** [comment]
You could use jsDelivr if you want http://cdn.jsdelivr.net/npm/clone
It auto minifies files.
http://cdn.jsdelivr.net/npm/clone@2.1.1/clone.js
http://cdn.jsdelivr.net/npm/clone@2.1.1/clone.min.js

**Comment by janat08** [comment]
ty
