### ISSUE TITLE
Latest tag on 1.0.4 instead of 2.1.1

### ISSUE THREAD

**Issue by davideicardi** [pvorb/clone#94]
With the release 1.0.4 the latest npm version is marked now as 1.0.4, [see here](https://www.npmjs.com/package/clone?activeTab=versions). I think that the latest should remain 2.1.1. Maybe you can fix using the following command:

`npm dist-tag rm clone latest`
`npm dist-tag add clone@2.1.1 latest`

See https://docs.npmjs.com/cli/dist-tag.

thanks

**Comment by pvorb** [comment]
Sorry, I didn't notice. Thanks for mentioning. I updated latest to clone@2.1.1.

BTW, for some reason I did not have to `rm` the tag first.
