### ISSUE TITLE
npm - No README

### ISSUE THREAD

**Issue by perry-mitchell** [pvorb/clone#95]
The readme doesn't seem to make it to npm, which is inconvenient. Would be nice to see the contents there rather than having to come through to github.

**Comment by knownasilya** [comment]
Saw the same thing just now.

**Comment by pvorb** [comment]
Thanks for mentioning. That was quite weird. I tagged version 2.1.1 as `latest` and now the README shows again. The README also was part of 1.0.4, which was the previous `latest`, so maybe npm just needed some change to re-render the README.
