### ISSUE TITLE
What is the 1.x -> 2.x breaking change?

### ISSUE THREAD

**Issue by landau** [pvorb/clone#96]
I see a `major` version change from 1.x -> 2.x. Assuming this repo follows semver semantics, what breaking change was introduced?

Thanks for your time on this project.

**Comment by pvorb** [comment]
Nothing broke with 2.0.0. I just introduced support for ES6 Maps and Sets.

I intend to never break the API of this library.

**Comment by landau** [comment]
Thanks. When following `semver`, `major` is reserved for api incompatible changes. 👍
